=== hati2002/Advance-JAva/XmlDemo/first.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT college (studend)>
<!ELEMENT studend (name,branch,id,address)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT branch (#PCDATA)>
<!ELEMENT id (#PCDATA)>

<!ELEMENT address (state,dis,pin)>
<!ELEMENT state (#PCDATA)>
<!ELEMENT dis (#PCDATA)>
<!ELEMENT pin (#PCDATA)>

=== hati2002/Advance-JAva/XmlDemo/first.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE college SYSTEM "first.dtd">
<college>
<studend>
<name>Suman</name>
<branch>Ece</branch>
<id>1901298306</id>
<address>
<state>WB</state>
<dis>East medinipur</dis>
<pin>721448</pin>
</address>
</studend>
</college>
